require "Definitions/ContainerButtonIcons"

ContainerButtonIcons = ContainerButtonIcons or {}
ContainerButtonIcons.ATARoofTent = getTexture("media/ui/commonlibrary/Container_ATARoofTent.png")
ContainerButtonIcons.ATARoofRackToolbox = getTexture("media/ui/commonlibrary/Container_ATARoofToolbox.png")
ContainerButtonIcons.ATAInteractiveTrunkRoofRack = getTexture("media/ui/commonlibrary/Container_ATAInteractiveTrunkRoofRack.png")
ContainerButtonIcons.ATAInteractiveTrunkWindowRearRack = getTexture("media/ui/commonlibrary/Container_ATAInteractiveTrunkWindowsRack.png")
ContainerButtonIcons.ATAInteractiveTrunkWheelRack = getTexture("media/ui/commonlibrary/Container_ATAInteractiveTrunkWheelRack.png")
ContainerButtonIcons.portablemicrowave = getTexture("media/ui/Container_Microwave.png")
ContainerButtonIcons.seatboxwooden = getTexture("media/ui/commonlibrary/Container_seatBoxWooden.png")
ContainerButtonIcons.ATABagOnProtectionWindowFrontLeft = getTexture("media/ui/commonlibrary/Container_Duffelbag.png")
ContainerButtonIcons.ATAInteractiveTrunkFront = getTexture("media/ui/commonlibrary/Container_quad_front.png")
ContainerButtonIcons.ATAInteractiveTrunkRear = getTexture("media/ui/commonlibrary/Container_quad_back.png")
ContainerButtonIcons.ATABagMotoLeft = getTexture("media/ui/commonlibrary/Container_universal_icon.png")
ContainerButtonIcons.ATABagMotoRight = getTexture("media/ui/commonlibrary/Container_universal_icon.png")
ContainerButtonIcons.ATABagMotoHolsterLeft = getTexture("media/ui/commonlibrary/Container_harley_holster.png")
ContainerButtonIcons.ATABagMotoHolsterRight = getTexture("media/ui/commonlibrary/Container_harley_holster.png")
ContainerButtonIcons.FreestorageFrontLeft = getTexture("media/ui/commonlibrary/Container_TCFloor.png")
ContainerButtonIcons.FreestorageFrontRight = getTexture("media/ui/commonlibrary/Container_TCFloor.png")
ContainerButtonIcons.FreestorageMiddleLeft = getTexture("media/ui/commonlibrary/Container_TCFloor.png")
ContainerButtonIcons.FreestorageMiddleRight = getTexture("media/ui/commonlibrary/Container_TCFloor.png")
ContainerButtonIcons.FreestorageRearLeft = getTexture("media/ui/commonlibrary/Container_TCFloor.png")
ContainerButtonIcons.FreestorageRearRight = getTexture("media/ui/commonlibrary/Container_TCFloor.png")
